### PR TITLE
Move rei config to default config

### PR DESCRIPTION
**Pull request by redcatone**
REI config should be outside regular config folder to prevent overriding user options (keybinds, favorited items, etc.) on modpack update.

### CODE REVIEW

**Comment by TheStaticVoid** [comment]
Had issues with this not being copied over sometimes, will have to test it again.

**Comment by TheStaticVoid** [comment]
I've tested having the config in the `defaultoptions` folder and the `defaultoptions/extra` folder, but it doesn't get copied on first run.

**Comment by redcatone** [comment]
After some testing I don't think there is a good resolution as it is not possible to ship a default config for the root folder.

I believe the `defaultoptions/` folder is for per world configs and not general configs on first launch. Files in `defaultoptions/` seem to get copied to the saves folder on world creation and not on client startup.

The `defaultoptions/extra/config/` folder would have worked but due to loading order it seems `REI` generates a fresh config first before `defaultoptions` checks and copies the config over.

Seems like the options are just:
1. Leave as is and override user REI settings on modpack update
1. Remove REI from config and leave recipe book enabled by default
1. Remove REI from config and use another mod like [norecipebook-fabric](https://www.curseforge.com/minecraft/mc-mods/norecipebook-fabric) to disable recipe book

**Comment by TheStaticVoid** [comment]
One thing I'm struggling to find a replacement for is how REI hides the recipe toasts if you disable the crafting book. 
I've tried both [Hidden Recipe Book](https://www.curseforge.com/minecraft/mc-mods/hidden-recipe-book) and [No Recipe Book](https://www.curseforge.com/minecraft/mc-mods/norecipebook-fabric), and they both don't fix this issue either.

**Comment by TheStaticVoid** [comment]
Going to punt this to next patch I think until we can figure out a better solution.

**Comment by redcatone** [comment]
> One thing I'm struggling to find a replacement for is how REI hides the recipe toasts if you disable the crafting book. I've tried both [Hidden Recipe Book](https://www.curseforge.com/minecraft/mc-mods/hidden-recipe-book) and [No Recipe Book](https://www.curseforge.com/minecraft/mc-mods/norecipebook-fabric), and they both don't fix this issue either.

Perhaps [Toast Manager](https://www.curseforge.com/minecraft/mc-mods/toast-manager) would work?

**Comment by TheStaticVoid** [comment]
Oh nice you were able to find something. The Curseforge search was failing me big time

**Comment by TheStaticVoid** [comment]
Fixed in https://github.com/TheStaticVoid/StaTech-Industry/commit/aeae1e7febb6be0c4501d340039fd938c31700b5

**Pull request closed without merging**
